name = "FABL"
version = "0.1.0"
description = "Formal Analysis of Boolean Functions in Lean"
keywords = ["mathematics", "boolean-functions", "fourier-analysis", "formalization"]
license = "Apache-2.0"
defaultTargets = ["FABL"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
warningAsError = true
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.0"

[[require]]
name = "ProbabilityApproximation"
git = "https://github.com/Polarnova/ProbabilityApproximation.git"
rev = "v0.9.5"

[[lean_lib]]
name = "FABL"
