/-
Copyright (c) 2026 Asher Yan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Asher Yan with Codex
-/
module

public import FABL.Chapter01.CubeCardinality
public import FABL.Chapter06.Pseudorandomness.FourierFourthMoment
public import Mathlib.Analysis.Seminorm
public import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
public import Mathlib.Data.Fin.Embedding

/-!
# Gowers inner products and norms

Book item: Exercise 6.34(a)--(i).

The Gowers inner product is kept on the additive binary cube. Its recursive coordinate split
uses `Fin.insertNthEquiv`; the Gowers--Cauchy--Schwarz argument iterates the finite-expectation
Cauchy--Schwarz inequality along an embedded family of active cube coordinates.
-/

open Finset
open scoped BigOperators BooleanCube

set_option autoImplicit false

@[expose] public section

namespace FABL

variable {n k r : ℕ}

/-- A family of real-valued binary-cube functions indexed by the vertices of a `k`-cube. -/
abbrev GowersFamily (n k : ℕ) := F₂Cube k → F₂Cube n → ℝ

/-- The point at vertex `s` of the affine cube generated by `x` and the directions `y`. -/
def gowersCubePoint (x : F₂Cube n) (y : Fin k → F₂Cube n) (s : F₂Cube k) :
    F₂Cube n :=
  x + ∑ i, (s i) • y i

/-- O'Donnell, Exercise 6.34: the `k`th Gowers inner product. -/
noncomputable def gowersInner (F : GowersFamily n k) : ℝ :=
  𝔼 y : Fin k → F₂Cube n, 𝔼 x : F₂Cube n,
    ∏ s : F₂Cube k, F s (gowersCubePoint x y s)

/-- The diagonal Gowers inner product. -/
noncomputable def gowersDiagonalInner (k : ℕ) (f : F₂Cube n → ℝ) : ℝ :=
  gowersInner (fun _ : F₂Cube k ↦ f)

/-- O'Donnell, Exercise 6.34: the `k`th Gowers uniformity quantity. -/
noncomputable def gowersNorm (k : ℕ) (f : F₂Cube n → ℝ) : ℝ :=
  gowersDiagonalInner k f ^ (((2 ^ k : ℕ) : ℝ)⁻¹)

/-- The one-dimensional cube vertex with bit `b`. -/
def gowersBit (b : 𝔽₂) : F₂Cube 1 :=
  fun _ ↦ b

/-- The two-dimensional cube vertex with first bit `a` and last bit `b`. -/
def gowersPair (a b : 𝔽₂) : F₂Cube 2 :=
  Fin.snoc (fun _ : Fin 1 ↦ a) b

/-- Splitting both a direction tuple and a vertex tuple at the same coordinate preserves the
affine-cube point after translating the base point by the removed contribution. -/
theorem gowersCubePoint_insertNth
    (i : Fin (k + 1)) (x h : F₂Cube n)
    (y : Fin k → F₂Cube n) (b : 𝔽₂) (s : F₂Cube k) :
    gowersCubePoint x (Fin.insertNth i h y) (Fin.insertNth i b s) =
      gowersCubePoint (x + b • h) y s := by
  unfold gowersCubePoint
  rw [Fin.sum_univ_succAbove _ i]
  simp only [Fin.insertNth_apply_same, Fin.insertNth_apply_succAbove]
  abel

/-- The product over binary vertices splits according to the last bit. -/
theorem prod_f₂Cube_succ {M : Type*} [CommMonoid M]
    (f : F₂Cube (k + 1) → M) :
    (∏ s, f s) =
      (∏ t : F₂Cube k, f (Fin.snoc t 0)) *
        ∏ t : F₂Cube k, f (Fin.snoc t 1) := by
  let e := Fin.snocEquiv (fun _ : Fin (k + 1) ↦ 𝔽₂)
  calc
    (∏ s, f s) = ∏ p : 𝔽₂ × F₂Cube k, f (e p) :=
      (e.prod_comp f).symm
    _ = ∏ b : 𝔽₂, ∏ t : F₂Cube k, f (Fin.snoc t b) := by
      rw [Fintype.prod_prod_type]
      rfl
    _ = (∏ t : F₂Cube k, f (Fin.snoc t 0)) *
        ∏ t : F₂Cube k, f (Fin.snoc t 1) := by
      rw [← (ZMod.finEquiv 2).toEquiv.prod_comp, Fin.prod_univ_two]
      rfl

private theorem prod_ite_mem_compl
    {ι M : Type*} [Fintype ι] [DecidableEq ι] [CommMonoid M]
    (A : Finset ι) (f g : ι → M) :
    (∏ i, if i ∈ A then f i else g i) =
      (∏ i ∈ A, f i) * ∏ i ∈ Aᶜ, g i := by
  have hA : (Finset.univ.filter fun i : ι ↦ i ∈ A) = A := by
    ext
    simp
  have hAc : (Finset.univ.filter fun i : ι ↦ i ∉ A) = Aᶜ := by
    ext
    simp
  simpa only [hA, hAc] using
    (Finset.prod_ite (s := (Finset.univ : Finset ι))
      (p := fun i : ι ↦ i ∈ A) f g)

private theorem expect_prod_type
    {α β : Type*} [Fintype α] [Fintype β] (f : α × β → ℝ) :
    (𝔼 p : α × β, f p) = 𝔼 a : α, 𝔼 b : β, f (a, b) := by
  rw [show (Finset.univ : Finset (α × β)) =
      (Finset.univ : Finset α) ×ˢ (Finset.univ : Finset β) by ext p; simp,
    Finset.expect_product]

private theorem expect_mul_add_eq_mul_expect
    (a b : F₂Cube n → ℝ) :
    (𝔼 h : F₂Cube n, 𝔼 x : F₂Cube n, a x * b (x + h)) =
      (𝔼 x, a x) * 𝔼 x, b x := by
  calc
    (𝔼 h : F₂Cube n, 𝔼 x : F₂Cube n, a x * b (x + h)) =
        𝔼 x : F₂Cube n, 𝔼 h : F₂Cube n, a x * b (x + h) := by
      exact Finset.expect_comm Finset.univ Finset.univ _
    _ = 𝔼 x : F₂Cube n, 𝔼 z : F₂Cube n, a x * b z := by
      apply Finset.expect_congr rfl
      intro x _
      apply Fintype.expect_equiv (Equiv.addLeft x)
      intro h
      rfl
    _ = (𝔼 x, a x) * 𝔼 z, b z :=
      (Fintype.expect_mul_expect a b).symm

/-- The half-cube product obtained by fixing coordinate `i` to `b`. -/
noncomputable def gowersHalfProductAt
    (F : GowersFamily n (k + 1)) (i : Fin (k + 1)) (b : 𝔽₂)
    (x : F₂Cube n) (y : Fin k → F₂Cube n) : ℝ :=
  ∏ s : F₂Cube k,
    F (Fin.insertNth i b s) (gowersCubePoint x y s)

/-- The half-cube expectation obtained by fixing coordinate `i` to `b`. -/
noncomputable def gowersHalfExpectationAt
    (F : GowersFamily n (k + 1)) (i : Fin (k + 1)) (b : 𝔽₂)
    (y : Fin k → F₂Cube n) : ℝ :=
  𝔼 x : F₂Cube n, gowersHalfProductAt F i b x y

/-- The half-cube expectation obtained by fixing the last coordinate. -/
noncomputable def gowersHalfExpectation
    (F : GowersFamily n (k + 1)) (b : 𝔽₂)
    (y : Fin k → F₂Cube n) : ℝ :=
  gowersHalfExpectationAt F (Fin.last k) b y

private theorem gowersProduct_insertNth
    (F : GowersFamily n (k + 1)) (i : Fin (k + 1))
    (x h : F₂Cube n) (y : Fin k → F₂Cube n) :
    (∏ s : F₂Cube (k + 1),
        F s (gowersCubePoint x (Fin.insertNth i h y) s)) =
      gowersHalfProductAt F i 0 x y *
        gowersHalfProductAt F i 1 (x + h) y := by
  let e := Fin.insertNthEquiv (fun _ : Fin (k + 1) ↦ 𝔽₂) i
  calc
    (∏ s : F₂Cube (k + 1),
        F s (gowersCubePoint x (Fin.insertNth i h y) s)) =
        ∏ p : 𝔽₂ × F₂Cube k,
          F (Fin.insertNth i p.1 p.2)
            (gowersCubePoint x (Fin.insertNth i h y)
              (Fin.insertNth i p.1 p.2)) :=
      (e.prod_comp fun s ↦
        F s (gowersCubePoint x (Fin.insertNth i h y) s)).symm
    _ = ∏ p : 𝔽₂ × F₂Cube k,
          F (Fin.insertNth i p.1 p.2)
            (gowersCubePoint (x + p.1 • h) y p.2) := by
      apply Finset.prod_congr rfl
      intro p _
      rw [gowersCubePoint_insertNth]
    _ = ∏ b : 𝔽₂, ∏ s : F₂Cube k,
          F (Fin.insertNth i b s)
            (gowersCubePoint (x + b • h) y s) := by
      rw [Fintype.prod_prod_type]
    _ = gowersHalfProductAt F i 0 x y *
        gowersHalfProductAt F i 1 (x + h) y := by
      rw [← (ZMod.finEquiv 2).toEquiv.prod_comp, Fin.prod_univ_two]
      simp [gowersHalfProductAt]

/-- Exercise 6.34(c), in coordinate-independent form: removing any direction makes the two
half-cube base points independent. -/
theorem gowersInner_split_at
    (F : GowersFamily n (k + 1)) (i : Fin (k + 1)) :
    gowersInner F =
      𝔼 y : Fin k → F₂Cube n,
        gowersHalfExpectationAt F i 0 y *
          gowersHalfExpectationAt F i 1 y := by
  let e := Fin.insertNthEquiv
    (fun _ : Fin (k + 1) ↦ F₂Cube n) i
  calc
    gowersInner F =
        𝔼 p : F₂Cube n × (Fin k → F₂Cube n),
          𝔼 x : F₂Cube n,
            ∏ s : F₂Cube (k + 1),
              F s (gowersCubePoint x (Fin.insertNth i p.1 p.2) s) := by
      unfold gowersInner
      symm
      apply Fintype.expect_equiv e
      intro p
      rfl
    _ = 𝔼 h : F₂Cube n, 𝔼 y : Fin k → F₂Cube n,
          𝔼 x : F₂Cube n,
            ∏ s : F₂Cube (k + 1),
              F s (gowersCubePoint x (Fin.insertNth i h y) s) := by
      rw [expect_prod_type]
    _ = 𝔼 h : F₂Cube n, 𝔼 y : Fin k → F₂Cube n,
          𝔼 x : F₂Cube n,
            gowersHalfProductAt F i 0 x y *
              gowersHalfProductAt F i 1 (x + h) y := by
      apply Finset.expect_congr rfl
      intro h _
      apply Finset.expect_congr rfl
      intro y _
      apply Finset.expect_congr rfl
      intro x _
      exact gowersProduct_insertNth F i x h y
    _ = 𝔼 y : Fin k → F₂Cube n, 𝔼 h : F₂Cube n,
          𝔼 x : F₂Cube n,
            gowersHalfProductAt F i 0 x y *
              gowersHalfProductAt F i 1 (x + h) y := by
      exact Finset.expect_comm Finset.univ Finset.univ _
    _ = 𝔼 y : Fin k → F₂Cube n,
          gowersHalfExpectationAt F i 0 y *
            gowersHalfExpectationAt F i 1 y := by
      apply Finset.expect_congr rfl
      intro y _
      exact expect_mul_add_eq_mul_expect
        (gowersHalfProductAt F i 0 · y)
        (gowersHalfProductAt F i 1 · y)

/-- Exercise 6.34(c), equation (6.9), with the last coordinate split off. -/
theorem gowersInner_succ (F : GowersFamily n (k + 1)) :
    gowersInner F =
      𝔼 y : Fin k → F₂Cube n,
        gowersHalfExpectation F 0 y * gowersHalfExpectation F 1 y :=
  gowersInner_split_at F (Fin.last k)

/-- Overwriting one cube coordinate produces the duplicated family used in the
Gowers--Cauchy--Schwarz iteration. -/
def gowersDuplicateAt
    (F : GowersFamily n k) (i : Fin k) (b : 𝔽₂) :
    GowersFamily n k :=
  fun s ↦ F (Function.update s i b)

/-- The book's family `f_s^(b)`, obtained by copying the `b` half across the last bit. -/
def gowersLastDuplicate
    (F : GowersFamily n (k + 1)) (b : 𝔽₂) :
    GowersFamily n (k + 1) :=
  gowersDuplicateAt F (Fin.last k) b

@[simp] theorem gowersLastDuplicate_apply
    (F : GowersFamily n (k + 1)) (b : 𝔽₂) (s : F₂Cube (k + 1)) :
    gowersLastDuplicate F b s = F (Fin.snoc (Fin.init s) b) := by
  simp [gowersLastDuplicate, gowersDuplicateAt, ← Fin.insertNth_removeNth,
    Fin.removeNth_last, Fin.insertNth_last']

/-- The inner product of a duplicated family is the expectation of a square. -/
theorem gowersInner_duplicateAt
    (F : GowersFamily n (k + 1)) (i : Fin (k + 1)) (b : 𝔽₂) :
    gowersInner (gowersDuplicateAt F i b) =
      𝔼 y : Fin k → F₂Cube n,
        gowersHalfExpectationAt F i b y ^ 2 := by
  calc
    gowersInner (gowersDuplicateAt F i b) =
        𝔼 y : Fin k → F₂Cube n,
          gowersHalfExpectationAt (gowersDuplicateAt F i b) i 0 y *
            gowersHalfExpectationAt (gowersDuplicateAt F i b) i 1 y :=
      gowersInner_split_at _ _
    _ = 𝔼 y : Fin k → F₂Cube n,
          gowersHalfExpectationAt F i b y ^ 2 := by
      apply Finset.expect_congr rfl
      intro y _
      have hhalf (c : 𝔽₂) :
          gowersHalfExpectationAt (gowersDuplicateAt F i b) i c y =
            gowersHalfExpectationAt F i b y := by
        unfold gowersHalfExpectationAt gowersHalfProductAt
        apply Finset.expect_congr rfl
        intro x _
        apply Finset.prod_congr rfl
        intro s _
        simp [gowersDuplicateAt]
      rw [hhalf 0, hhalf 1, pow_two]

/-- Every duplicated-family inner product is nonnegative. -/
theorem gowersInner_duplicateAt_nonneg
    (F : GowersFamily n (k + 1)) (i : Fin (k + 1)) (b : 𝔽₂) :
    0 ≤ gowersInner (gowersDuplicateAt F i b) := by
  rw [gowersInner_duplicateAt]
  exact Finset.expect_nonneg fun y _ ↦ sq_nonneg _

/-- Exercise 6.34(d): every diagonal Gowers inner product of positive dimension is
nonnegative. -/
theorem gowersDiagonalInner_nonneg (k : ℕ) (f : F₂Cube n → ℝ) :
    0 ≤ gowersDiagonalInner (k + 1) f := by
  let F : GowersFamily n (k + 1) := fun _ ↦ f
  have hduplicate :
      gowersDuplicateAt F (Fin.last k) 0 = F := by
    funext s
    rfl
  change 0 ≤ gowersInner F
  rw [← hduplicate]
  exact gowersInner_duplicateAt_nonneg F (Fin.last k) 0

/-- The Gowers quantity is nonnegative in every positive dimension. -/
theorem gowersNorm_nonneg (hk : 0 < k) (f : F₂Cube n → ℝ) :
    0 ≤ gowersNorm k f := by
  obtain ⟨r, rfl⟩ := Nat.exists_eq_succ_of_ne_zero hk.ne'
  exact Real.rpow_nonneg (gowersDiagonalInner_nonneg r f) _

/-- Raising a positive-dimensional Gowers quantity to `2^k` recovers its diagonal inner
product. -/
theorem gowersNorm_pow (hk : 0 < k) (f : F₂Cube n → ℝ) :
    gowersNorm k f ^ (2 ^ k) = gowersDiagonalInner k f := by
  obtain ⟨r, rfl⟩ := Nat.exists_eq_succ_of_ne_zero hk.ne'
  unfold gowersNorm
  exact Real.rpow_inv_natCast_pow
    (gowersDiagonalInner_nonneg r f) (by positivity)

/-- Exercise 6.34(e), with an arbitrary coordinate chosen for the duplicated halves. -/
theorem gowers_cauchy_schwarz_at
    (F : GowersFamily n k) (i : Fin k) :
    gowersInner F ≤
      √(gowersInner (gowersDuplicateAt F i 0)) *
        √(gowersInner (gowersDuplicateAt F i 1)) := by
  cases k with
  | zero => exact Fin.elim0 i
  | succ k =>
      calc
        gowersInner F =
            𝔼 y : Fin k → F₂Cube n,
              gowersHalfExpectationAt F i 0 y *
                gowersHalfExpectationAt F i 1 y :=
          gowersInner_split_at F i
        _ ≤ √(gowersInner (gowersDuplicateAt F i 0)) *
            √(gowersInner (gowersDuplicateAt F i 1)) := by
          let A := fun y : Fin k → F₂Cube n ↦
            gowersHalfExpectationAt F i 0 y
          let B := fun y : Fin k → F₂Cube n ↦
            gowersHalfExpectationAt F i 1 y
          have hA : 0 ≤ 𝔼 y, A y ^ 2 :=
            Finset.expect_nonneg fun y _ ↦ sq_nonneg _
          have hB : 0 ≤ 𝔼 y, B y ^ 2 :=
            Finset.expect_nonneg fun y _ ↦ sq_nonneg _
          have hcs :
              (𝔼 y, A y * B y) ^ 2 ≤
                (𝔼 y, A y ^ 2) * 𝔼 y, B y ^ 2 := by
            simpa using Finset.expect_mul_sq_le_sq_mul_sq
              (Finset.univ : Finset (Fin k → F₂Cube n)) A B
          calc
            (𝔼 y, A y * B y) ≤ |𝔼 y, A y * B y| := le_abs_self _
            _ ≤ √((𝔼 y, A y ^ 2) * 𝔼 y, B y ^ 2) :=
              Real.abs_le_sqrt hcs
            _ = √(𝔼 y, A y ^ 2) * √(𝔼 y, B y ^ 2) := by
              rw [Real.sqrt_mul hA]
            _ = √(gowersInner (gowersDuplicateAt F i 0)) *
                √(gowersInner (gowersDuplicateAt F i 1)) := by
              rw [gowersInner_duplicateAt, gowersInner_duplicateAt]

/-- Exercise 6.34(e): Cauchy--Schwarz for the two families obtained by fixing the last bit. -/
theorem gowers_cauchy_schwarz_last (F : GowersFamily n (k + 1)) :
    gowersInner F ≤
      √(gowersInner (gowersLastDuplicate F 0)) *
        √(gowersInner (gowersLastDuplicate F 1)) :=
  gowers_cauchy_schwarz_at F (Fin.last k)

/-- A vertex family restricted along an embedding of its active coordinates. -/
def gowersLiftFamilyAlong
    (e : Fin r ↪ Fin k) (F : GowersFamily n r) :
    GowersFamily n k :=
  fun s ↦ F (fun i ↦ s (e i))

/-- Fixing the last active coordinate of a lifted family gives the corresponding lifted
half-family. -/
theorem gowersDuplicateAt_liftFamilyAlong
    (e : Fin (r + 1) ↪ Fin k) (F : GowersFamily n (r + 1)) (b : 𝔽₂) :
    gowersDuplicateAt (gowersLiftFamilyAlong e F) (e (Fin.last r)) b =
      gowersLiftFamilyAlong (Fin.castSuccEmb.trans e)
        (fun s : F₂Cube r ↦ F (Fin.snoc s b)) := by
  funext s x
  apply congrArg (fun t ↦ F t x)
  funext q
  refine Fin.lastCases ?_ (fun j ↦ ?_) q
  · simp
  · have hne : e j.castSucc ≠ e (Fin.last r) := by
      intro h
      exact Fin.castSucc_ne_last j (e.injective h)
    simp [hne]

/-- The iterated Cauchy--Schwarz expression for an `r`-dimensional family, with all leaf
diagonal products evaluated in ambient dimension `k`. -/
noncomputable def gowersCSBound (k : ℕ) :
    (r : ℕ) → GowersFamily n r → ℝ
  | 0, F => gowersDiagonalInner k (F 0)
  | r + 1, F =>
      √(gowersCSBound k r (fun s ↦ F (Fin.snoc s 0))) *
        √(gowersCSBound k r (fun s ↦ F (Fin.snoc s 1)))

/-- Iterating the one-coordinate Cauchy--Schwarz inequality bounds every lifted active family
by its Cauchy--Schwarz leaf expression. -/
theorem gowersInner_liftFamilyAlong_le_csBound
    (e : Fin r ↪ Fin k) (F : GowersFamily n r) :
    gowersInner (gowersLiftFamilyAlong e F) ≤ gowersCSBound k r F := by
  induction r with
  | zero =>
      have hconstant :
          gowersLiftFamilyAlong e F = fun _ ↦ F 0 := by
        funext s x
        apply congrArg (fun t ↦ F t x)
        funext i
        exact Fin.elim0 i
      rw [hconstant]
      change gowersDiagonalInner k (F 0) ≤ gowersDiagonalInner k (F 0)
      exact le_rfl
  | succ r ih =>
      let e' : Fin r ↪ Fin k := Fin.castSuccEmb.trans e
      let F₀ : GowersFamily n r := fun s ↦ F (Fin.snoc s 0)
      let F₁ : GowersFamily n r := fun s ↦ F (Fin.snoc s 1)
      have hcs := gowers_cauchy_schwarz_at
        (gowersLiftFamilyAlong e F) (e (Fin.last r))
      rw [gowersDuplicateAt_liftFamilyAlong,
        gowersDuplicateAt_liftFamilyAlong] at hcs
      have h₀ : gowersInner (gowersLiftFamilyAlong e' F₀) ≤
          gowersCSBound k r F₀ :=
        ih e' F₀
      have h₁ : gowersInner (gowersLiftFamilyAlong e' F₁) ≤
          gowersCSBound k r F₁ :=
        ih e' F₁
      calc
        gowersInner (gowersLiftFamilyAlong e F) ≤
            √(gowersInner (gowersLiftFamilyAlong e' F₀)) *
              √(gowersInner (gowersLiftFamilyAlong e' F₁)) := by
          simpa [e', F₀, F₁] using hcs
        _ ≤ √(gowersCSBound k r F₀) * √(gowersCSBound k r F₁) := by
          exact mul_le_mul (Real.sqrt_le_sqrt h₀) (Real.sqrt_le_sqrt h₁)
            (Real.sqrt_nonneg _) (Real.sqrt_nonneg _)
        _ = gowersCSBound k (r + 1) F := by
          rfl

private theorem sqrt_prod_gowersDiagonal_rpow
    (hk : 0 < k) (r : ℕ) (F : GowersFamily n r) :
    √(∏ s : F₂Cube r,
        gowersDiagonalInner k (F s) ^ (((2 ^ r : ℕ) : ℝ)⁻¹)) =
      ∏ s : F₂Cube r,
        gowersDiagonalInner k (F s) ^ (((2 ^ (r + 1) : ℕ) : ℝ)⁻¹) := by
  rw [Real.sqrt_eq_rpow]
  have hfactor (s : F₂Cube r) :
      0 ≤ gowersDiagonalInner k (F s) ^ (((2 ^ r : ℕ) : ℝ)⁻¹) :=
    Real.rpow_nonneg
      (by
        obtain ⟨q, rfl⟩ := Nat.exists_eq_succ_of_ne_zero hk.ne'
        exact gowersDiagonalInner_nonneg q (F s))
      _
  rw [← Real.finsetProd_rpow Finset.univ
    (fun s : F₂Cube r ↦
      gowersDiagonalInner k (F s) ^ (((2 ^ r : ℕ) : ℝ)⁻¹))
    (fun s _ ↦ hfactor s) (1 / 2 : ℝ)]
  apply Finset.prod_congr rfl
  intro s _
  rw [← Real.rpow_mul
    (by
      obtain ⟨q, rfl⟩ := Nat.exists_eq_succ_of_ne_zero hk.ne'
      exact gowersDiagonalInner_nonneg q (F s))]
  congr 1
  push_cast
  norm_num [pow_succ]
  ring

/-- The iterated Cauchy--Schwarz expression is the product of equal fractional powers of its
diagonal leaves. -/
theorem gowersCSBound_eq_prod_rpow
    (hk : 0 < k) (r : ℕ) (F : GowersFamily n r) :
    gowersCSBound k r F =
      ∏ s : F₂Cube r,
        gowersDiagonalInner k (F s) ^ (((2 ^ r : ℕ) : ℝ)⁻¹) := by
  induction r with
  | zero =>
      simp only [gowersCSBound, pow_zero, Nat.cast_one, inv_one,
        Real.rpow_one]
      exact (Fintype.prod_subsingleton
        (fun s : F₂Cube 0 ↦ gowersDiagonalInner k (F s)) 0).symm
  | succ r ih =>
      rw [gowersCSBound, ih, ih,
        sqrt_prod_gowersDiagonal_rpow hk,
        sqrt_prod_gowersDiagonal_rpow hk]
      exact (prod_f₂Cube_succ fun s : F₂Cube (r + 1) ↦
        gowersDiagonalInner k (F s) ^
          (((2 ^ (r + 1) : ℕ) : ℝ)⁻¹)).symm

/-- At full depth, the Cauchy--Schwarz leaf expression is the product of Gowers quantities. -/
theorem gowersCSBound_eq_prod_norm
    (hk : 0 < k) (F : GowersFamily n k) :
    gowersCSBound k k F = ∏ s, gowersNorm k (F s) := by
  rw [gowersCSBound_eq_prod_rpow hk]
  rfl

/-- Exercise 6.34(f), equation (6.10): the Gowers--Cauchy--Schwarz inequality. -/
theorem gowers_cauchy_schwarz
    (hk : 0 < k) (F : GowersFamily n k) :
    gowersInner F ≤ ∏ s, gowersNorm k (F s) := by
  have hlift := gowersInner_liftFamilyAlong_le_csBound
    (e := Function.Embedding.refl (Fin k)) F
  rw [show gowersLiftFamilyAlong (Function.Embedding.refl (Fin k)) F = F by
    funext s x
    rfl] at hlift
  rw [gowersCSBound_eq_prod_norm hk] at hlift
  exact hlift

/-- Exercise 6.34(a): the first Gowers inner product is the product of the two means. -/
theorem gowersInner_one_eq (F : GowersFamily n 1) :
    gowersInner F =
      mean (F (gowersBit 0)) * mean (F (gowersBit 1)) := by
  have hvertex (b : 𝔽₂) (t : F₂Cube 0) :
      Fin.cons b t = gowersBit b := by
    funext i
    fin_cases i
    simp [gowersBit]
  rw [gowersInner_succ]
  simp [gowersHalfExpectation, gowersHalfExpectationAt,
    gowersHalfProductAt, gowersCubePoint, mean]
  simp only [hvertex]

/-- Exercise 6.34(a): the square of `U¹` is the square of the mean. -/
theorem gowersNorm_one_sq (f : F₂Cube n → ℝ) :
    gowersNorm 1 f ^ 2 = mean f ^ 2 := by
  have hpow := gowersNorm_pow (k := 1) (by norm_num) f
  norm_num at hpow
  rw [hpow, gowersDiagonalInner, gowersInner_one_eq]
  ring

private theorem gowersHalfExpectation_two_eq_convolution
    (F : GowersFamily n 2) (b : 𝔽₂)
    (y : Fin 1 → F₂Cube n) :
    gowersHalfExpectation F b y =
      convolution (F (gowersPair 0 b)) (F (gowersPair 1 b)) (y 0) := by
  have hinsert (a : 𝔽₂) (t : F₂Cube 0) :
      Fin.insertNth (Fin.last 1) b (Fin.snoc t a) =
        gowersPair a b := by
    rw [Fin.insertNth_last', Fin.snoc_zero]
    rfl
  rw [convolution_apply_add]
  unfold gowersHalfExpectation gowersHalfExpectationAt gowersHalfProductAt
  apply Finset.expect_congr rfl
  intro x _
  rw [prod_f₂Cube_succ]
  rw [Fintype.prod_subsingleton _ (0 : F₂Cube 0),
    Fintype.prod_subsingleton _ (0 : F₂Cube 0)]
  rw [hinsert 0 0, hinsert 1 0]
  simp [gowersCubePoint, Fin.snoc_zero, add_comm]

/-- Exercise 6.34(b): the mixed `U²` inner product is the pointwise fourth Fourier
coefficient sum. -/
theorem gowersInner_two_eq_fourier (F : GowersFamily n 2) :
    gowersInner F =
      ∑ γ : F₂Cube n,
        vectorFourierCoeff (F (gowersPair 0 0)) γ *
          vectorFourierCoeff (F (gowersPair 1 0)) γ *
          vectorFourierCoeff (F (gowersPair 0 1)) γ *
          vectorFourierCoeff (F (gowersPair 1 1)) γ := by
  rw [gowersInner_succ]
  simp_rw [gowersHalfExpectation_two_eq_convolution]
  calc
    (𝔼 y : Fin 1 → F₂Cube n,
        convolution (F (gowersPair 0 0)) (F (gowersPair 1 0)) (y 0) *
          convolution (F (gowersPair 0 1)) (F (gowersPair 1 1)) (y 0)) =
        𝔼 t : F₂Cube n,
          convolution (F (gowersPair 0 0)) (F (gowersPair 1 0)) t *
            convolution (F (gowersPair 0 1)) (F (gowersPair 1 1)) t := by
      apply Fintype.expect_equiv (Equiv.funUnique (Fin 1) (F₂Cube n))
      intro y
      rfl
    _ = ∑ γ : F₂Cube n,
          vectorFourierCoeff
              (convolution (F (gowersPair 0 0)) (F (gowersPair 1 0))) γ *
            vectorFourierCoeff
              (convolution (F (gowersPair 0 1)) (F (gowersPair 1 1))) γ :=
      vector_plancherel _ _
    _ = ∑ γ : F₂Cube n,
        vectorFourierCoeff (F (gowersPair 0 0)) γ *
          vectorFourierCoeff (F (gowersPair 1 0)) γ *
          vectorFourierCoeff (F (gowersPair 0 1)) γ *
          vectorFourierCoeff (F (gowersPair 1 1)) γ := by
      apply Finset.sum_congr rfl
      intro γ _
      rw [vectorFourierCoeff_convolution, vectorFourierCoeff_convolution]
      ring

/-- Exercise 6.34(b): the fourth power of `U²` is the fourth spectral moment. -/
theorem gowersNorm_two_pow_four_eq (f : F₂Cube n → ℝ) :
    gowersNorm 2 f ^ 4 = vectorFourierFourthMoment f := by
  have hpow := gowersNorm_pow (k := 2) (by norm_num) f
  norm_num at hpow
  rw [hpow, gowersDiagonalInner, gowersInner_two_eq_fourier,
    vectorFourierFourthMoment]
  apply Finset.sum_congr rfl
  intro γ _
  ring

/-- The constant-one function has Gowers quantity one in every positive dimension. -/
@[simp] theorem gowersNorm_one (hk : 0 < k) :
    gowersNorm k (fun _ : F₂Cube n ↦ (1 : ℝ)) = 1 := by
  apply (pow_left_inj₀ (gowersNorm_nonneg hk _) zero_le_one
    (by positivity : (2 ^ k : ℕ) ≠ 0)).mp
  rw [gowersNorm_pow hk]
  simp [gowersDiagonalInner, gowersInner]

/-- The family used to compare consecutive Gowers quantities. -/
def gowersMonotonicityFamily (f : F₂Cube n → ℝ) :
    GowersFamily n (k + 1) :=
  fun s ↦ if s (Fin.last k) = 0 then f else 1

private theorem gowersInner_monotonicityFamily
    (f : F₂Cube n → ℝ) :
    gowersInner (gowersMonotonicityFamily (k := k) f) =
      gowersDiagonalInner k f := by
  rw [gowersInner_succ]
  unfold gowersHalfExpectation gowersHalfExpectationAt gowersHalfProductAt
  simp [gowersMonotonicityFamily, gowersDiagonalInner, gowersInner]

private theorem prod_gowersNorm_monotonicityFamily
    (f : F₂Cube n → ℝ) :
    (∏ s : F₂Cube (k + 1),
        gowersNorm (k + 1) (gowersMonotonicityFamily f s)) =
      gowersNorm (k + 1) f ^ (2 ^ k) := by
  have hzero (t : F₂Cube k) :
      gowersMonotonicityFamily f (Fin.snoc t 0) = f := by
    simp only [gowersMonotonicityFamily, Fin.snoc_last, if_pos]
  have hone (t : F₂Cube k) :
      gowersMonotonicityFamily f (Fin.snoc t 1) =
        (fun _ : F₂Cube n ↦ (1 : ℝ)) := by
    unfold gowersMonotonicityFamily
    rw [Fin.snoc_last, if_neg (by norm_num : (1 : 𝔽₂) ≠ 0)]
    funext x
    rfl
  rw [prod_f₂Cube_succ]
  calc
    (∏ t : F₂Cube k,
        gowersNorm (k + 1) (gowersMonotonicityFamily f (Fin.snoc t 0))) *
        ∏ t : F₂Cube k,
          gowersNorm (k + 1) (gowersMonotonicityFamily f (Fin.snoc t 1)) =
        (∏ _t : F₂Cube k, gowersNorm (k + 1) f) *
          ∏ _t : F₂Cube k,
            gowersNorm (k + 1) (fun _ : F₂Cube n ↦ (1 : ℝ)) := by
      apply congrArg₂ (· * ·)
      · apply Finset.prod_congr rfl
        intro t _
        rw [hzero]
      · apply Finset.prod_congr rfl
        intro t _
        rw [hone]
    _ = gowersNorm (k + 1) f ^ (2 ^ k) *
        gowersNorm (k + 1) (fun _ : F₂Cube n ↦ (1 : ℝ)) ^ (2 ^ k) := by
      simp only [Finset.prod_const, Finset.card_univ, card_f₂Cube]
    _ = gowersNorm (k + 1) f ^ (2 ^ k) := by
      rw [gowersNorm_one (Nat.zero_lt_succ k), one_pow, mul_one]

/-- Exercise 6.34(g): Gowers quantities are monotone in their positive dimension. -/
theorem gowersNorm_mono (hk : 0 < k) (f : F₂Cube n → ℝ) :
    gowersNorm k f ≤ gowersNorm (k + 1) f := by
  have hcs := gowers_cauchy_schwarz (k := k + 1) (by omega)
    (gowersMonotonicityFamily (k := k) f)
  rw [gowersInner_monotonicityFamily,
    prod_gowersNorm_monotonicityFamily] at hcs
  apply le_of_pow_le_pow_left₀ (by positivity : (2 ^ k : ℕ) ≠ 0)
    (gowersNorm_nonneg (by omega) f)
  rw [gowersNorm_pow hk]
  exact hcs

/-- Select `f` or `g` independently at every vertex of the Gowers cube. -/
def gowersChoiceFamily
    (f g : F₂Cube n → ℝ) (A : Finset (F₂Cube k)) :
    GowersFamily n k :=
  fun s ↦ if s ∈ A then f else g

/-- The diagonal inner product of a sum expands into all vertexwise choices of the two
summands. -/
theorem gowersDiagonalInner_add_expansion
    (f g : F₂Cube n → ℝ) :
    gowersDiagonalInner k (f + g) =
      ∑ A : Finset (F₂Cube k), gowersInner (gowersChoiceFamily f g A) := by
  classical
  unfold gowersDiagonalInner gowersInner
  calc
    (𝔼 y : Fin k → F₂Cube n, 𝔼 x : F₂Cube n,
        ∏ s : F₂Cube k, (f + g) (gowersCubePoint x y s)) =
        𝔼 y : Fin k → F₂Cube n, 𝔼 x : F₂Cube n,
          ∑ A : Finset (F₂Cube k),
            ∏ s : F₂Cube k,
              gowersChoiceFamily f g A s (gowersCubePoint x y s) := by
      apply Finset.expect_congr rfl
      intro y _
      apply Finset.expect_congr rfl
      intro x _
      simp only [Pi.add_apply]
      rw [Fintype.prod_add]
      apply Finset.sum_congr rfl
      intro A _
      symm
      simp only [gowersChoiceFamily, ite_apply]
      exact prod_ite_mem_compl A _ _
    _ = 𝔼 y : Fin k → F₂Cube n,
          ∑ A : Finset (F₂Cube k), 𝔼 x : F₂Cube n,
            ∏ s : F₂Cube k,
              gowersChoiceFamily f g A s (gowersCubePoint x y s) := by
      apply Finset.expect_congr rfl
      intro y _
      rw [Finset.expect_sum_comm]
    _ = ∑ A : Finset (F₂Cube k),
          𝔼 y : Fin k → F₂Cube n, 𝔼 x : F₂Cube n,
            ∏ s : F₂Cube k,
              gowersChoiceFamily f g A s (gowersCubePoint x y s) := by
      rw [Finset.expect_sum_comm]

private theorem sum_prod_gowersNorm_choice
    (f g : F₂Cube n → ℝ) :
    (∑ A : Finset (F₂Cube k),
        ∏ s : F₂Cube k, gowersNorm k (gowersChoiceFamily f g A s)) =
      (gowersNorm k f + gowersNorm k g) ^ (2 ^ k) := by
  classical
  calc
    (∑ A : Finset (F₂Cube k),
        ∏ s : F₂Cube k, gowersNorm k (gowersChoiceFamily f g A s)) =
        ∑ A : Finset (F₂Cube k),
          (∏ s ∈ A, gowersNorm k f) *
            ∏ s ∈ Aᶜ, gowersNorm k g := by
      apply Finset.sum_congr rfl
      intro A _
      simp only [gowersChoiceFamily, apply_ite]
      exact prod_ite_mem_compl A _ _
    _ = ∏ _s : F₂Cube k, (gowersNorm k f + gowersNorm k g) :=
      (Fintype.prod_add _ _).symm
    _ = (gowersNorm k f + gowersNorm k g) ^ (2 ^ k) := by
      rw [Finset.prod_const, Finset.card_univ, card_f₂Cube]

/-- Exercise 6.34(h): the Gowers quantity satisfies the triangle inequality. -/
theorem gowersNorm_add_le
    (hk : 0 < k) (f g : F₂Cube n → ℝ) :
    gowersNorm k (f + g) ≤ gowersNorm k f + gowersNorm k g := by
  have hinner :
      gowersDiagonalInner k (f + g) ≤
        (gowersNorm k f + gowersNorm k g) ^ (2 ^ k) := by
    rw [gowersDiagonalInner_add_expansion]
    calc
      (∑ A : Finset (F₂Cube k),
          gowersInner (gowersChoiceFamily f g A)) ≤
          ∑ A : Finset (F₂Cube k),
            ∏ s : F₂Cube k,
              gowersNorm k (gowersChoiceFamily f g A s) := by
        apply Finset.sum_le_sum
        intro A _
        exact gowers_cauchy_schwarz hk _
      _ = (gowersNorm k f + gowersNorm k g) ^ (2 ^ k) :=
        sum_prod_gowersNorm_choice f g
  apply le_of_pow_le_pow_left₀ (by positivity : (2 ^ k : ℕ) ≠ 0)
    (add_nonneg (gowersNorm_nonneg hk f) (gowersNorm_nonneg hk g))
  rw [gowersNorm_pow hk]
  exact hinner

private theorem pow_two_pow_eq_abs_pow_two_pow
    (hk : 0 < k) (a : ℝ) :
    a ^ (2 ^ k) = |a| ^ (2 ^ k) := by
  obtain ⟨r, rfl⟩ := Nat.exists_eq_succ_of_ne_zero hk.ne'
  exact (Even.pow_abs (Even.pow_of_ne_zero even_two (by positivity)) a).symm

/-- Scaling every vertex factor scales the diagonal inner product by the corresponding
`2^k`th power. -/
theorem gowersDiagonalInner_smul
    (a : ℝ) (f : F₂Cube n → ℝ) :
    gowersDiagonalInner k (a • f) =
      a ^ (2 ^ k) * gowersDiagonalInner k f := by
  unfold gowersDiagonalInner gowersInner
  calc
    (𝔼 y : Fin k → F₂Cube n, 𝔼 x : F₂Cube n,
        ∏ s : F₂Cube k, (a • f) (gowersCubePoint x y s)) =
        𝔼 y : Fin k → F₂Cube n, 𝔼 x : F₂Cube n,
          a ^ (2 ^ k) *
            ∏ s : F₂Cube k, f (gowersCubePoint x y s) := by
      apply Finset.expect_congr rfl
      intro y _
      apply Finset.expect_congr rfl
      intro x _
      simp only [Pi.smul_apply, smul_eq_mul, Finset.prod_mul_distrib,
        Finset.prod_const, Finset.card_univ, card_f₂Cube]
    _ = 𝔼 y : Fin k → F₂Cube n,
          a ^ (2 ^ k) *
            (𝔼 x : F₂Cube n,
              ∏ s : F₂Cube k, f (gowersCubePoint x y s)) := by
      apply Finset.expect_congr rfl
      intro y _
      rw [← Finset.mul_expect]
    _ = a ^ (2 ^ k) *
        (𝔼 y : Fin k → F₂Cube n, 𝔼 x : F₂Cube n,
          ∏ s : F₂Cube k, f (gowersCubePoint x y s)) := by
      rw [← Finset.mul_expect]

/-- The Gowers quantity is absolutely homogeneous. -/
theorem gowersNorm_smul
    (hk : 0 < k) (a : ℝ) (f : F₂Cube n → ℝ) :
    gowersNorm k (a • f) = |a| * gowersNorm k f := by
  apply (pow_left_inj₀
    (gowersNorm_nonneg hk (a • f))
    (mul_nonneg (abs_nonneg a) (gowersNorm_nonneg hk f))
    (by positivity : (2 ^ k : ℕ) ≠ 0)).mp
  rw [gowersNorm_pow hk, gowersDiagonalInner_smul,
    pow_two_pow_eq_abs_pow_two_pow hk, mul_pow, gowersNorm_pow hk]

/-- Exercise 6.34(h): the positive-dimensional Gowers quantity as a Mathlib `Seminorm`. -/
noncomputable def gowersSeminorm (k : ℕ) (hk : 0 < k) :
    Seminorm ℝ (F₂Cube n → ℝ) :=
  Seminorm.of (gowersNorm k) (gowersNorm_add_le hk) fun a f ↦ by
    simpa [Real.norm_eq_abs] using gowersNorm_smul hk a f

/-- Every `U²` quantity is bounded by every higher-dimensional Gowers quantity. -/
theorem gowersNorm_two_le (hk : 2 ≤ k) (f : F₂Cube n → ℝ) :
    gowersNorm 2 f ≤ gowersNorm k f := by
  induction k with
  | zero => omega
  | succ k ih =>
      by_cases h : k = 1
      · subst k
        exact le_rfl
      · exact (ih (by omega)).trans (gowersNorm_mono (by omega) f)

/-- Exercise 6.34(i): for `k ≥ 2`, vanishing Gowers quantity implies that the function
vanishes. -/
theorem eq_zero_of_gowersNorm_eq_zero
    (hk : 2 ≤ k) (f : F₂Cube n → ℝ) (hf : gowersNorm k f = 0) :
    f = 0 := by
  have htwo : gowersNorm 2 f = 0 := by
    apply le_antisymm
    · exact (gowersNorm_two_le hk f).trans_eq hf
    · exact gowersNorm_nonneg (by norm_num) f
  have hmoment : vectorFourierFourthMoment f = 0 := by
    rw [← gowersNorm_two_pow_four_eq, htwo]
    norm_num
  have hsum :
      (∑ γ : F₂Cube n, vectorFourierCoeff f γ ^ 4) = 0 := by
    simpa [vectorFourierFourthMoment] using hmoment
  have hcoeff (γ : F₂Cube n) : vectorFourierCoeff f γ = 0 := by
    have hpow :
        vectorFourierCoeff f γ ^ 4 = 0 :=
      (Finset.sum_eq_zero_iff_of_nonneg
        (fun δ (_ : δ ∈ (Finset.univ : Finset (F₂Cube n))) ↦
          by positivity)).mp hsum γ (Finset.mem_univ γ)
    exact (pow_eq_zero_iff (by norm_num : (4 : ℕ) ≠ 0)).mp hpow
  funext x
  rw [vector_fourier_expansion f x]
  simp [hcoeff]

end FABL
